import Head from 'next/head';
import React from 'react';
import Header from './Header';
import Navbar from './Navbar';

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />

      {/* Navbar */}
      <Navbar />

      {/* SearchBox */}
      <div className="max-w-6xl mx-auto py-4">{children}</div>
    </>
  );
}
